kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafdrop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop-ui
  template:
    metadata:
      labels:
        app: kafdrop-ui
    spec:
      containers:
      - name: kafdrop-ui
        image: obsidiandynamics/kafdrop
        ports:
        - containerPort: 9000
        env:
        - name: JVM_OPTS
          value: "-Xms512M -Xms512M"
        - name: SERVER_SERVLET_CONTEXTPATH
          value: "/"
        - name: KAFKA_BROKERCONNECT
          value: "192.168.4.39:9092"
        - name: SERVER_PORT
          value: "9000"