apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - name: port9092 
          containerPort: 9092
        - name: port9094
          containerPort: 9094
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 127.0.0.1
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        # Create a topic NAME:PARTITION:REPLICAS
        - name: KAFKA_CREATE_TOPICS
          value: TOPIC_A:3:1, TOPIC_B:3:1
        - name: KAFKA_LISTENERS #kafka 가 내부적으로 바인딩하는 주소
          value: INTERNAL://127.0.0.1:9092,EXTERNAL://127.0.0.1:9094
        - name: KAFKA_ADVERTISED_LISTENERS #kafka 프로듀서, 컨슈머에게 노출할 주소, default: KAFKA_LISTENER
          value: INTERNAL://127.0.0.1:9092,EXTERNAL://127.0.0.1:9094
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL