apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-bemily-messenger-kafka-01
  namespace: bemily-messenger-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
        app: dev-bemily-messenger-kafka-01
        id: "0"
  template:
    metadata:
      labels:
        app: dev-bemily-messenger-kafka-01
        id: "0"
    spec:
      containers:
      - name: dev-bemily-messenger-kafka-01
        image: bitnami/kafka:latest
        ports:
        - name: port9092 
          containerPort: 9092
        - name: port9094
          containerPort: 9094
        env:
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_CFG_LISTENERS
          value: CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: CLIENT://:9092,EXTERNAL://127.0.0.1:9093
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: CLIENT
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: dev-bemily-messenger-kafka-zookeer-01:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"