kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-bemily-messenger-kafka-zookeer-01
  namespace: bemily-messenger-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-bemily-messenger-kafka-zookeer-01
  template:
    metadata:
      labels:
        app: dev-bemily-messenger-kafka-zookeer-01
    spec:
      containers:
      - name: zoo1
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_SERVER_ID
          value: "1"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
