apiVersion: v1
kind: Service
metadata:
  name: dev-bemily-messenger-kafka-zookeer-01
  namespace: bemily-messenger-kafka
  labels:
    app: dev-bemily-messenger-kafka-zookeer-01
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: dev-bemily-messenger-kafka-zookeer-01